import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import pokemons from "./pokemons.json";
import SearchBar from "./SearchBar";

const Home: NextPage = () => {
  const [searchQuery, setSearchQuery] = useState("");
  const [filteredPokemons, setFilteredPokemons] = useState(pokemons);

  useEffect(() => {
    if (searchQuery === "") {
      setFilteredPokemons(pokemons);
    } else {
      setFilteredPokemons(
        pokemons.filter((pokemon) =>
          pokemon.frenchName.toLowerCase().startsWith(searchQuery)
        )
      );
    }
  }, [searchQuery]);

  return (
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center ">
        <div className="dark:bg-slate-900 px-6 py-8">
          <SearchBar
            searchQuery={searchQuery}
            setSearchQuery={setSearchQuery}
          />
          <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-8 gap-4 lg:gap-8 ">
            {filteredPokemons.map((pokemon: any) => {
              return (
                <div
                  className="border dark:bg-slate-800 text-white rounded-md flex flex-col justify-end text-center hover:font-bold 	cursor-pointer"
                  key={pokemon.frenchName}
                >
                  <img src={pokemon.sprite} className="mx-auto w-20 h-20" />
                  <p>{pokemon.frenchName}</p>
                </div>
              );
            })}
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}></footer> */}
    </div>
  );
};

export default Home;
