import type { NextPage } from "next";
import Head from "next/head";
import { useContext, useEffect, useState } from "react";

import SearchBar from "./Components/SearchBar";
import index from "./api/index";
import { IPokemon } from "interfaces/IPokemon";
import Loader from "./Components/Loader";
import AllPokemons from "./Components/PokemonGrid";
import PokemonContext from "../contexts/pokemon";

const Home: NextPage = () => {
  const [searchQuery, setSearchQuery] = useState("");
  const [filteredPokemons, setFilteredPokemons] = useState<IPokemon[]>([]);
  const { pokemons, addPokemons } = useContext<any>(PokemonContext);

  useEffect(() => {
    if (!pokemons.pokemonsGrid.length) {
      const fetchData = async () => {
        const result = await index();
        addPokemons(result);
        setFilteredPokemons(result.pokemonsGrid);
      };
      fetchData().catch(console.error);
    } else {
      setFilteredPokemons(pokemons.pokemonsGrid);
    }
  }, [addPokemons, pokemons.pokemonsGrid]);

  useEffect(() => {
    if (searchQuery === "") {
      setFilteredPokemons(pokemons.pokemonsGrid);
    } else {
      setFilteredPokemons(
        pokemons.pokemonsGrid.filter((pokemon: { name: string }) =>
          pokemon.name.toLowerCase().startsWith(searchQuery)
        )
      );
    }
  }, [pokemons, searchQuery]);

  return (
    <div>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-center ">
        <div className="dark:bg-slate-900 px-6 py-8">
          <SearchBar
            searchQuery={searchQuery}
            setSearchQuery={setSearchQuery}
            isActivate={pokemons.length === 0}
          />
          {pokemons.pokemonsGrid.length && (
            <AllPokemons filteredPokemons={filteredPokemons} />
          )}
        </div>
        {!pokemons.pokemonsGrid.length && <Loader />}
      </main>

      {/* <footer className={styles.footer}></footer> */}
    </div>
  );
};

export default Home;
